[package]
name = "color2filter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "color2filter"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = ["dep:clap"]

[dependencies]
clap = { version = "4.6.7", features = ["derive"], optional = true }
cobyla = "1.0.4"
cordic = "0.1.5"
csscolorparser = "0.9.0"
fixed = "1.31.0"
oklab = "1.1.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.129" }
